import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { BotIcon, DatabaseBackupIcon, GitPullRequestIcon } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-svh bg-background`}
      >
        <div className="relative flex min-h-svh flex-col">
          {/* Hero */}
          <div>
            <div className="px-6 py-12 max-w-5xl mx-auto border-x border-dashed">
              <h1 className="text-2xl font-bold leading-tight tracking-tighter sm:text-3xl md:text-4xl lg:leading-[1.1]">
                Förderkompass
              </h1>
              <p className="text-base font-light text-foreground sm:text-lg pt-2">
                Fördermöglichkeiten sollen sichtbar und nutzbar gemacht werden.
                Daher wird im ersten Schritt automatisiert eine einheitliche
                Datenbasis aus verschiedenen Quellen erstellt, die anschließend
                von Unternehmen und Vereinen genutzt werden kann.
              </p>
            </div>
          </div>
          <div className="border-y border-dashed">
            <nav className="p-6 flex gap-2 max-w-5xl mx-auto border-x border-dashed">
              <Button asChild variant="outline">
                <Link href="/">
                  <DatabaseBackupIcon /> Datenbasis
                </Link>
              </Button>
              <Button asChild variant="outline">
                <Link href="/fragebogen">
                  <GitPullRequestIcon />
                  Fragebogen
                </Link>
              </Button>
              <Button asChild variant="outline">
                <Link href="/chat">
                  <BotIcon /> KI Chat
                </Link>
              </Button>
            </nav>
          </div>
          <main className="max-w-5xl w-full mx-auto border-x border-dashed flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
